export const GET_COURSE_LIST = 'GET_COURSE_LIST'
export const GET_COURSE = 'GET_COURSE'

export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_USER_COURSE = 'GET_USER_COURSE'
export const JOIN_TO_COURSE = 'JOIN_TO_COURSE'

export const GET_LESSON_LIST = 'GET_LESSON_LIST'
export const GET_LESSON = 'GET_LESSON'

export const GET_SCHEDULE_LIST = 'GET_SCHEDULE_LIST'
export const GET_SCHEDULE = 'GET_SCHEDULE'

export const GET_CSRF_TOKEN = 'GET_CSRF_TOKEN'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'